# Generated by Django 3.2.4 on 2021-06-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20210603_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testclass',
            name='Humidity',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='testclass',
            name='Nitrogen',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='testclass',
            name='PH',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='testclass',
            name='Phosphorus',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='testclass',
            name='Potassium',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='testclass',
            name='Rainfall',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='testclass',
            name='Temperature',
            field=models.CharField(max_length=200),
        ),
    ]
